// M4-01 email magic-link authentication: storage for sign-in links and
// server-side sessions.
//
// Same driver-agnostic design as db/billing-repository.ts — it depends only
// on drizzle-orm/sqlite-core's generic BaseSQLiteDatabase, never on
// drizzle-orm/d1 or `cloudflare:workers` — so the whole authentication path
// is unit-testable against real SQLite under plain Node
// (tests/magic-link.test.mts) rather than against a re-implementation of it.
//
// Two invariants hold everywhere in this file:
//
//   * No raw secret is ever written. The link token and the session id are
//     generated by the caller, and only their SHA-256 digests reach a column.
//     A dump of these tables therefore yields nothing that can be presented
//     back to the server as a credential.
//   * Every single-use or bounded decision is made by ONE guarded write and
//     read off `result.meta.changes` (D1's rows-affected). A read followed by
//     a write would let two concurrent requests both observe "not yet
//     consumed" and both proceed; SQLite/D1 serialize writers, so exactly one
//     of two racing guarded writes can ever see one row changed.
import { and, eq, gt, isNull, lt, sql } from "drizzle-orm";
import * as schema from "./schema";
import type { AppDatabase } from "./repository";

const { authMagicLinkTokens, authSessions, users } = schema;

/**
 * Resolved server-side identity. `userId` is the local `users.id`, already
 * mapped — call sites never re-derive it from anything a client sent.
 */
export interface SessionIdentity {
  userId: string;
  externalSubject: string;
  email: string;
  displayName: string;
}

/** See the identical helpers in db/billing-repository.ts and db/repository.ts. */
function rowsChanged(result: unknown): number {
  const changes = (result as { meta?: { changes?: number } } | undefined)?.meta?.changes;
  return typeof changes === "number" ? changes : 0;
}

/** How many expired rows one opportunistic sweep removes. Bounded so sign-in never becomes an unbounded scan. */
const SWEEP_BATCH = 50;

/**
 * How stale `lastSeenAt` may get before a resolution refreshes it. Writing on
 * every request would double the cost of every authenticated read for a field
 * nothing makes a decision on; never writing would leave the column a
 * duplicate of `createdAt` and make an idle-session policy impossible to add
 * later.
 */
const TOUCH_INTERVAL_MS = 15 * 60 * 1000;

export async function insertMagicLinkToken(
  db: AppDatabase,
  input: { tokenDigest: string; email: string; issuedAt: Date; expiresAt: Date; browserNonceDigest?: string | null },
): Promise<void> {
  await db.insert(authMagicLinkTokens).values({
    id: crypto.randomUUID(),
    tokenDigest: input.tokenDigest,
    email: input.email,
    createdAt: input.issuedAt,
    expiresAt: input.expiresAt,
    // SEC-17: the digest of the nonce cookie set on the requesting browser,
    // never the nonce. Null when the request could not carry one (plain http
    // on a non-dev host), which makes one-click redemption impossible for
    // that link rather than making it unauthenticated.
    browserNonceDigest: input.browserNonceDigest ?? null,
  });
}

/**
 * SEC-17. Single-use redemption that ALSO requires the presented nonce to
 * match the one stored against the row — that is, requires this to be the
 * browser that asked for the link.
 *
 * One guarded UPDATE, decided by rows-affected, exactly like
 * `consumeMagicLinkToken`: the nonce test lives in the WHERE clause rather
 * than in a read followed by a write, so two concurrent redemptions cannot
 * both observe an unconsumed row, and a stored digest is never read back out
 * and string-compared against anything.
 *
 * It records no failed attempt. A nonce mismatch is not evidence of
 * link-guessing — it is the ordinary case of opening the link on a phone —
 * and the caller answers it with a confirmation step, not a refusal.
 */
export async function consumeMagicLinkTokenForBrowser(
  db: AppDatabase,
  input: { tokenDigest: string; nonceDigest: string; now: Date },
): Promise<{ email: string } | null> {
  const consumed = await db
    .update(authMagicLinkTokens)
    .set({ consumedAt: input.now, attemptCount: sql`${authMagicLinkTokens.attemptCount} + 1` })
    .where(and(
      eq(authMagicLinkTokens.tokenDigest, input.tokenDigest),
      isNull(authMagicLinkTokens.consumedAt),
      gt(authMagicLinkTokens.expiresAt, input.now),
      eq(authMagicLinkTokens.browserNonceDigest, input.nonceDigest),
    ));
  if (rowsChanged(consumed) !== 1) return null;

  const [row] = await db
    .select({ email: authMagicLinkTokens.email })
    .from(authMagicLinkTokens)
    .where(eq(authMagicLinkTokens.tokenDigest, input.tokenDigest))
    .limit(1);
  return row ? { email: row.email } : null;
}

/**
 * Records a redemption attempt against a digest that did not redeem.
 *
 * Split out of `consumeMagicLinkToken`'s fallback so the GET path can count an
 * attempt exactly once, on the branch where it knows the link is dead. It is
 * deliberately a no-op for a digest that was never issued: it creates no row
 * an attacker can probe for, and it changes nothing the caller is told.
 */
export async function recordMagicLinkAttempt(db: AppDatabase, tokenDigest: string): Promise<void> {
  await db
    .update(authMagicLinkTokens)
    .set({ attemptCount: sql`${authMagicLinkTokens.attemptCount} + 1` })
    .where(eq(authMagicLinkTokens.tokenDigest, tokenDigest));
}

/**
 * The address a still-live link would sign someone in as, or null.
 *
 * Read-only and deliberately so: it decides which PAGE to render, never
 * whether a session is created. The single-use decision stays where it has
 * always been — one guarded write, either `consumeMagicLinkTokenForBrowser`
 * on the one-click path or `consumeMagicLinkToken` on the confirmed POST — so
 * this is not the read half of a read-then-write.
 *
 * Expired, spent, and never-issued all return null, so the failure the caller
 * renders stays the single indistinguishable one.
 */
export async function findRedeemableMagicLinkToken(
  db: AppDatabase,
  input: { tokenDigest: string; now: Date },
): Promise<{ email: string } | null> {
  const [row] = await db
    .select({ email: authMagicLinkTokens.email })
    .from(authMagicLinkTokens)
    .where(and(
      eq(authMagicLinkTokens.tokenDigest, input.tokenDigest),
      isNull(authMagicLinkTokens.consumedAt),
      gt(authMagicLinkTokens.expiresAt, input.now),
    ))
    .limit(1);
  return row ? { email: row.email } : null;
}

/**
 * Single-use redemption. Returns the target address exactly once per token.
 *
 * A second redemption, an expired token, and a digest that was never issued
 * all return `null` — the caller cannot tell them apart, and neither can an
 * attacker, which is why the sign-in route reports one message for all three.
 */
export async function consumeMagicLinkToken(
  db: AppDatabase,
  input: { tokenDigest: string; now: Date },
): Promise<{ email: string } | null> {
  const consumed = await db
    .update(authMagicLinkTokens)
    .set({ consumedAt: input.now, attemptCount: sql`${authMagicLinkTokens.attemptCount} + 1` })
    .where(and(
      eq(authMagicLinkTokens.tokenDigest, input.tokenDigest),
      isNull(authMagicLinkTokens.consumedAt),
      gt(authMagicLinkTokens.expiresAt, input.now),
    ));

  if (rowsChanged(consumed) !== 1) {
    // Record the failed attempt against the digest when one exists. This is a
    // no-op for an unknown digest, so it neither creates a row an attacker can
    // probe for nor changes what the caller is told.
    await db
      .update(authMagicLinkTokens)
      .set({ attemptCount: sql`${authMagicLinkTokens.attemptCount} + 1` })
      .where(eq(authMagicLinkTokens.tokenDigest, input.tokenDigest));
    return null;
  }

  const [row] = await db
    .select({ email: authMagicLinkTokens.email })
    .from(authMagicLinkTokens)
    .where(eq(authMagicLinkTokens.tokenDigest, input.tokenDigest))
    .limit(1);
  return row ? { email: row.email } : null;
}

/** Invalidates every outstanding link for an address. Used on a successful sign-in so a stale link in an inbox is dead. */
export async function consumeOutstandingLinksForEmail(
  db: AppDatabase,
  input: { email: string; now: Date },
): Promise<void> {
  await db
    .update(authMagicLinkTokens)
    .set({ consumedAt: input.now })
    .where(and(eq(authMagicLinkTokens.email, input.email), isNull(authMagicLinkTokens.consumedAt)));
}

export async function createSession(
  db: AppDatabase,
  input: { sessionDigest: string; userId: string; issuedAt: Date; expiresAt: Date },
): Promise<void> {
  await db.insert(authSessions).values({
    id: crypto.randomUUID(),
    sessionDigest: input.sessionDigest,
    userId: input.userId,
    createdAt: input.issuedAt,
    expiresAt: input.expiresAt,
    lastSeenAt: input.issuedAt,
  });
}

/**
 * Resolves a session digest to the identity behind it, or null.
 *
 * Server-side expiry is authoritative: the cookie's Max-Age is a client-side
 * convenience the client can ignore, so the expiry test lives here. A session
 * belonging to a deleted account resolves to nothing, which is what keeps a
 * cookie issued before an account deletion from outliving it.
 */
export async function findSessionIdentity(
  db: AppDatabase,
  input: { sessionDigest: string; now: Date },
): Promise<SessionIdentity | null> {
  const [row] = await db
    .select({
      userId: users.id,
      externalSubject: users.externalSubject,
      contactEmail: users.contactEmail,
      deletedAt: users.deletedAt,
      expiresAt: authSessions.expiresAt,
      lastSeenAt: authSessions.lastSeenAt,
    })
    .from(authSessions)
    .innerJoin(users, eq(users.id, authSessions.userId))
    .where(eq(authSessions.sessionDigest, input.sessionDigest))
    .limit(1);

  if (!row) return null;
  if (row.deletedAt) return null;
  if (row.expiresAt.getTime() <= input.now.getTime()) return null;

  // Throttled liveness. Best-effort by construction: a failure here must never
  // turn a signed-in customer into a signed-out one.
  if (input.now.getTime() - row.lastSeenAt.getTime() > TOUCH_INTERVAL_MS) {
    try { await touchSession(db, { sessionDigest: input.sessionDigest, now: input.now }); } catch { /* liveness is not a control */ }
  }

  const email = row.contactEmail ?? "";
  return { userId: row.userId, externalSubject: row.externalSubject, email, displayName: email || row.externalSubject };
}

/** Records liveness for an already-resolved session. Best-effort: a failure here must never fail a request. */
export async function touchSession(
  db: AppDatabase,
  input: { sessionDigest: string; now: Date },
): Promise<void> {
  await db
    .update(authSessions)
    .set({ lastSeenAt: input.now })
    .where(eq(authSessions.sessionDigest, input.sessionDigest));
}

/** Ends one session server-side. Clearing the cookie alone would leave the row usable if the value were captured. */
export async function deleteSession(db: AppDatabase, sessionDigest: string): Promise<void> {
  await db.delete(authSessions).where(eq(authSessions.sessionDigest, sessionDigest));
}

/**
 * Fixed-window admission, decided by rows-affected on one guarded upsert.
 *
 * The limit lives in the WHERE clause of the DO UPDATE, so the counter is
 * only incremented when it is still under the bound — two concurrent requests
 * at the boundary cannot both be admitted. Raw SQL because drizzle's insert
 * builder has no ON CONFLICT ... DO UPDATE ... WHERE form; this mirrors
 * DistributedPreviewRequestGuard's counter statement deliberately.
 */
export async function admitRateLimitedRequest(
  db: AppDatabase,
  input: { bucketKey: string; windowStart: number; limit: number; now: number },
): Promise<boolean> {
  const result = await db.run(sql`
    insert into auth_rate_limits (bucket_key, window_start, request_count, updated_at)
    values (${input.bucketKey}, ${input.windowStart}, 1, ${input.now})
    on conflict(bucket_key, window_start) do update set
      request_count = auth_rate_limits.request_count + 1,
      updated_at = excluded.updated_at
    where auth_rate_limits.request_count < ${input.limit}
  `);
  return rowsChanged(result) === 1;
}

/**
 * Opportunistic cleanup of spent authentication state, on the same pattern as
 * db/repository.ts's retention sweep: bounded, run from a write path, and
 * safe to fail. Expired rows are already inert — an expired session and a
 * consumed token both resolve to nothing — so this is hygiene, not a control.
 */
export async function purgeExpiredAuthRows(db: AppDatabase, now: Date, windowFloor: number): Promise<void> {
  const stale = await db
    .select({ id: authSessions.id })
    .from(authSessions)
    .where(lt(authSessions.expiresAt, now))
    .limit(SWEEP_BATCH);
  for (const row of stale) await db.delete(authSessions).where(eq(authSessions.id, row.id));

  const spent = await db
    .select({ id: authMagicLinkTokens.id })
    .from(authMagicLinkTokens)
    .where(lt(authMagicLinkTokens.expiresAt, now))
    .limit(SWEEP_BATCH);
  for (const row of spent) await db.delete(authMagicLinkTokens).where(eq(authMagicLinkTokens.id, row.id));

  await db.run(sql`delete from auth_rate_limits where window_start < ${windowFloor}`);
}
